env: "local" # local, dev, prod
storage_path: "./storage/storage.db" #only for sql lite
http_server:
  address: "localhost:8082"
  timeout: 4s # время на чтение запроса и такое же время на отправку ответа. Время на обработку не будет ограничено
  idle_timeout: 60s # время жизни соединения с клиентом. Если много запросов от одного клиента, то это одно соединение, если клиент долго не запрашивает, то такое соединение нужно обраывать